---
version: '3.8'
services:
 
  arxiv-train:  &arxiv_base
    image: paper2code/arxiv-qa:cpu-latest
    container_name: ${NAMESPACE}-train
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
    - elasticsearch
    networks:
    - internal
    volumes:
    - arxiv-data:/opt/data
    - ./server:/opt/service
    command: ["--train"]

  arxiv-qa:
    <<: *arxiv_base
    container_name: ${NAMESPACE}-server
    environment:
    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
    - internal
    - web
    ports:
    - 5018:5018
    command: ["--port", "5018", "--host", "0.0.0.0"]

  arxiv-meta:
    image: paper2code/gsutil:ubuntu-18.04
    container_name: ${NAMESPACE}-gsutil
    build:
      context: ./gsutil
      dockerfile: Dockerfile
    volumes:
    - arxiv-data:/opt/data
    command: ["cp", "-n", "gs://arxiv-dataset/metadata-v5/arxiv-metadata-oai.json", "."]

  elastic:
    image: blacktop/elasticsearch:7.8
    container_name: ${NAMESPACE}-elastic
    hostname: elastic
    networks:
    - internal
    ports:
    - 9200:9200
    environment:
    - discovery.type=single-node
    volumes:
    - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  arxiv-data:
  es-data:
