---
version: '3.8'
services:
 
  arxiv-train:  &arxiv_base
    image: paper2code/arxiv-qa:gpu-latest
    container_name: ${NAMESPACE}-train
    build:
      context: ./services/server
      dockerfile: Dockerfile.gpu
    depends_on:
    - elasticsearch
    networks:
    - internal
    volumes:
    - arxiv-data:/opt/data
    - ./services/server:/opt/service
    - ./shared/logs:/opt/logs
    command: ["--train"]

  arxiv-qa:
    <<: *arxiv_base
    container_name: ${NAMESPACE}-server
    environment:
    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
    - internal
    - web
    ports:
    - 5018:5018
    command: ["--port", "5018", "--host", "0.0.0.0"]

  arxiv-tg:
    image: paper2code/arxiv-tg:latest-py3-slim
    container_name: ${NAMESPACE}-telegram
    environment:
    - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    - TELEGRAM_ID_ADMIN=${TELEGRAM_ID_ADMIN}
    build:
      context: ./services/telegram
      dockerfile: Dockerfile
    networks:
    - internal
    volumes:
    - ./services/telegram:/opt/service
    - ./shared/logs:/opt/logs
    command: ["python3", "server.py"]

  arxiv-meta:
    image: paper2code/gsutil:4.9-alpine3.12
    container_name: ${NAMESPACE}-gsutil
    build:
      context: ./services/gsutil
      dockerfile: Dockerfile
    volumes:
    - arxiv-data:/opt/data
    command: ["cp", "-n", "gs://arxiv-dataset/metadata-v5/arxiv-metadata-oai.json", "."]

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: ${NAMESPACE}-elasticsearch
    networks:
    - internal
    environment:
    - discovery.type=single-node
    volumes:
    - es-data:/usr/share/elasticsearch/data
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

networks:
  internal:
    driver: bridge
  web:
    external: true

volumes:
  arxiv-data:
  es-data:
